### ISSUE TITLE
2015-05-23 International NodeSchool Day

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#102]
NodeSchool is a community driven, open source educational project that teaches JavaScript and node.js skills in an interactive, self-guided way. There are workshops available for every skill level from JS beginners all the way to experienced node programmers.

This event is part of [International NodeSchool Day](http://nodeschool.io/international-day/), so we'll be getting in touch with other NodeSchoolers around the world during the day.

You will need to bring your own laptop, and it will help if you have already installed node.js. We'll have plenty of mentors to help and guide you throughout the day.

See http://nodeschool.io/international-day/

#### Date

Saturday 23rd May 2015, 10:00am

#### Organisation

- [x] Add to Meetup.com
- [x] Add to SummerOfHacks.io
- [x] Add Meetup link to https://github.com/nodeschool/international-day/issues/22
- [x] Add organisers and participants to the [international-day team](https://github.com/orgs/nodeschool/teams/international-day) so we're on their roll-call.
- [x] Book pastries
- [x] Purchase snacks/drinks (see #101)

#### On the day
There's a load of information on  https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md.

- [x] Take a group photo
- [x] Record a mini-film saying 'hello from JSOxford' and add it [here](https://github.com/nodeschool/international-day/tree/2015/Video)?
- [x] Hangout with a NodeSchool group from far, far away (see [here](https://github.com/nodeschool/international-day/issues/8) for the list).

Part of the Summer of Hacks 2015 (#101).

**Comment by benfoxall** [comment]
hmm, would kind of screw with SoH plans - but there *is* http://nodeschool.io/international-day/ at the end of May

**Comment by spikeheap** [comment]
We could see if @omgmog and @LuRsT wanted to run Sushack 3 this weekend and then move NodeSchool forward a month?

**Comment by omgmog** [comment]
I'll grab a moment with @LuRsT today to talk about it!

**Comment by omgmog** [comment]
Alright we might be set for June 27th then -- will be a bit awkward for me as I'll not be working for 2degrees anymore by that point, but it shouldn't be an issue.

We'll get the dates out on social media and update the site soonish, to reflect the new SusHack 3 date

**Comment by spikeheap** [comment]
@omgmog, that's great, I've updated the dates for NodeSchool to fit. If the venue is awkward we can probably sort out White October. Also, just say the word if you want a hand with organising/sponsorship/etc. :+1:

**Comment by LuRsT** [comment]
No worries, I'm on the case, but I may take up your offer @spikeheap :+1:

**Comment by spikeheap** [comment]
I've enrolled us in International NodeSchool Day (https://github.com/nodeschool/international-day/issues/8#issuecomment-95060149) and updated our todo list above.

**Comment by spikeheap** [comment]
NodeSchool is fast approaching. There are a few shots we need to get for the international day video: https://github.com/nodeschool/international-day/issues/9#issuecomment-103419270.

**Comment by peterjwest** [comment]
I can't make it to this now, unfortunately, soz.

**Comment by benfoxall** [comment]
@peterjwest I've un-marked you as an organiser on github.  Do you want to rsvp no to let someone on the waitlist on?

**Comment by spikeheap** [comment]
NodeSchool was awesome. Particularly trampolining with Rich. 

To close this off we just need to:

- [ ] @benfoxall Invoice Haybrook for supplies (I've emailed a receipt to @benfoxall for snacks)
- [ ] @spikeheap Upload videos to the international nodeschool group
- [ ] @spikeheap Organise a writeup post (#119)

**Comment by AverageMarcus** [comment]
If people are happy with @richdouglasevans [writeup](https://github.com/jsoxford/jsoxford.github.com/issues/119#issuecomment-105003026) then I don't mind converting it to a post. Unless @richdouglasevans wants to do it himself?

**Comment by spikeheap** [comment]
I love @richdouglasevans writeup, but I agree with his original comment at the top of the issue that it would be nice to have a rough idea of how many people came, what they worked on, a kind of a micro-summary from JSOxford as a group.

It would be ace to have @richdouglasevans on the site too - perhaps we need to add support for authors in our theme?

**Comment by AverageMarcus** [comment]
I actually quite like that idea. I'm happy to update the theme to allow optional authors. Would be nice to show the community contributing. :smile:
