### ISSUE TITLE
Summer of Hacks Code Retreat (2014/07/06)

### ISSUE THREAD

**Issue by spikeheap** [jsoxford/jsoxford.github.com#32]
Breaking out of #26 for clarity.

 # Summer of Hacks Code Retreat
- _Date_: 6th July, 9:45 – 17:00(ish), then pub
- _Location_: The Jam Factory, Hollybush Row, 27 Park End St, Oxford OX1 1HU
## TODO
- [x] Find a sponsor for the venue!
- [x] Does the Jam Factory have whiteboards?
- [x] Find out catering prices from Jam Factory, could be a good option (BF: £35 coffee, £5pp sandwiches)
- [x] Finalise catering for morning & lunch, within £300. 
- [x] Agree kata (GoL, right?)
- [x] Sort out floorplan for space
- [x] Prep slides
- [x] Send out last-minute confirmation & prerequisites for day
- [x] Print out cheatsheets for the day (_the rules_)
- [x] Sponsorship - Mail out to oxford geeks for attendees / sponsorship
- [x] Sponsorship - (?) approach some companies/people directly
## Costs & sponsorship
- ~Breakfast snacks, max **£75** (25 \* £3)~ (we'll be starting at 10 think people should sort out before that)
- Lunch, max **£125** (25 \* £5)
- ~~Fruit/~~Tea/coffee/water~~/soft drinks~~ **£40** (this was plenty at NS)
- Post-retreat beer (if we have any leftover sponsorship?)
- Extra for the robots?

Haybrook IT are kindly sponsoring lunch & snacks. Breakfast should be self-funding using the ticket proceeds.

**We just need sponsorship for the venue, and possibly a round of drinks post-event.**
## Format

See:
- http://jscoderetreat.com/2/
- http://coderetreat.org/
- http://vimeo.com/18955165, introduction video by the creator of code retreat

As before, we'll suggest and promote TDD, particularly using TDDBin. This time though I want to pull back the emphasis on TDD from the exercises, so it's more just the way we're doing things rather than the point of the exercise.
### Kata

We'll do ~5 rounds of the same kata. We're using Game of Life again because it's got good scope for extension and is straightfoward.
### Restrictions
1. **Paper/pencil (non-matching language pairs)**. The aim is to get everyone comfortable with the problem, break the ice and start the discussion about generation format.
2. Subversive developer - one person writes test, other tries to subvert test with implementation.
3. Randori (no conditionals)
4. Immutables only
### Timings
- 9:45 meet for coffee/pastries
- 10:00 start - Haybrook pitch
- 10:05 intro to Code Retreat, what's the point
- 10:10 intro to kata
- 10:15 split into pairs
- 10:20 SESSION 1 (40 minutes)
- 11:00 retrospective & break (20 minutes)
- 12:00 SESSION 2 (50 minutes)
- 12:50 retrospective & break (20 minutes)
- 13:10 LUNCH!
- 14:10 SESSION 3 (50 minutes)
- 15:00 retrospective & break (20 minutes)
- 15:20 SESSION 4 (50 minutes)
- 16:10 retrospective & break (20 minutes)
- 16:30 final retrospective
- 17:00 head to the pub
## Pre-requisites for attendees
- Laptop & charger
- Dev environment for their chosen language including package manager (gem/npm/pip)
## Equipment
- Projector (x2 if possible)
- USB pen drives. Always useful for sharing last minute bits.
- Whiteboard pens or flipchart + markers
- Post its for retrospective?
- Extension leads
## Publicity
- [x] JSOxford blog post (http://jsoxford.com/2014/summer-of-hacks/)
- [x] Eventbrite tickets (https://www.eventbrite.co.uk/e/sumer-of-hacks-code-retreat-tickets-11906533763)
- [x] Tweet the hell out of it
