### ISSUE TITLE
Performance - January 22nd

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#46]
What do people think about having a performance themed meetup?

* emscripten - compiling c/c++ code into JS
* frontend js performance, browser rendering pipeline and where JS fits

**Comment by benfoxall** [comment]
## ACTION PLAN

We've had a meeting in the pub, and here are some things that need doing.

- [ ] @spikeheap sponsorship?
- [ ] @peterjwest sponsorship?
- [ ] @benfoxall email oxford geeks
- [ ] @spikeheap diversity
- [ ] @spikeheap @peterjwest @benfoxall tweet and share (tweet from jsox first)
- [ ] @benfoxall email speakers
- [ ] book area at Joe Perks
- [ ] plan next event

**Comment by c0g** [comment]
How long so I need to talk for and where do I need to go to to talk?

**Comment by c0g** [comment]
Where do I need to go to and how long do I need to talk?

**Comment by benfoxall** [comment]
@c0g I've just mailed you, White October - talks start at 7.30, however long you want (though half an hour might be a good max).  Do you have a talk title and description that we could update [meetup](http://www.meetup.com/JSOxford/) with?

**Comment by benfoxall** [comment]
:+1:
