### ISSUE TITLE
Post-jquk - 11th March

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/jsoxford.github.com#52]
It's [jQueryUK](http://jqueryuk.com/2015/) on the 6th, so it would be pretty cool to have a meetup alongside it.

~~There's a bit of a clash with [jQuizzy](http://jqueryuk.com/2015/schedule.php#fringe) on the Thursday - we could either move it to the Wednesday, or find some way for people to attend both?~~ **update - we've chosen the week after jquk**

We've got a great talk suggestion from @tomlane - #49 - might be cool to get that in?

I'm going to be pretty busy with jQueryUK, though @spikeheap has offered to take charge of this - whoop!

We're going to have some planning beers (or juice) on **Wednesday (14th) 5.30 at [Jo Perks](http://joeperksandco.co.uk/)** - totally come along (or throw some comments in here if you have any suggestions).

**Comment by tomlane** [comment]
![06c4438732db6baf7d18688310a5798a](https://cloud.githubusercontent.com/assets/642385/5684242/7b578a08-9826-11e4-8535-344ea46a43f6.gif)
![tumblr_inline_ng35fg27r61rxwd4i](https://cloud.githubusercontent.com/assets/642385/5684243/7b5bb632-9826-11e4-8b8e-50b49a892955.gif)

**Comment by benfoxall** [comment]
@tomlane yup! it *is* happening!  Really looking forward to it.

@spikeheap & @peterjwest - are you still up for planning/whatever in Jo Perks tonight?

**Comment by spikeheap** [comment]
@benfoxall @peterjwest seeing as we love the gifs right now:
![](http://images.sodahead.com/polls/001215147/bigstockphoto_Check_Yes_431128_answer_1_xlarge.jpeg)

**Comment by benfoxall** [comment]
On my way - http://glympse.com/0ECS-X68M

**Comment by benfoxall** [comment]
## ACTION PLAN

We've had a meeting in the pub, and here are some things that need doing.

- [ ] @spikeheap sponsorship?
- [ ] @peterjwest sponsorship?
- [ ] @benfoxall email oxford geeks
- [ ] @spikeheap diversity
- [ ] @spikeheap @peterjwest @benfoxall tweet and share (tweet from jsox first)
- [ ] @benfoxall email speakers
- [ ] book area at Joe Perks
- [ ] plan next event

**Comment by benfoxall** [comment]
(testing gitter integration…)

**Comment by benfoxall** [comment]
urgh

**Comment by richdouglasevans** [comment]
Yo JavaScripters!

Are we canning February's JSOxford meetup due to the imminent arrival of March's JS-heavy events. (JQueryUK.)

It's the 9th now: I'm happy to organise a JS February meetup at White October if folks are keen to a) have one, and b) step up with talks. It's kinda short notice though, so if we skip February that's fine too. I'll let this call hang for a couple of days to see if anyone nibbles.

**Comment by spikeheap** [comment]
Yo yo @richdouglasevans, I think we decided that having one around JQuery and one in Feb put them close together. Our initial aim was to have the even pre-JQuery, so that wouldn't have left much time at all in between. 

I'm away eating snow for the last half of Feb, so unfortunately I won't be able to come/help if anything does get arranged.

**Comment by richdouglasevans** [comment]
Ah ok, that's cool. I vaguely recalled reading that somewhere, but couldn't source it.

On that note then, are we gonna advertise the pre-JQueryUK event on the meetup page then? I'd suggest we do, and early. I think I have write access to that page, so how about I whip up some blurb with links to JQueryUK and stick it up?

**Comment by benfoxall** [comment]
# Possible planning meet - 7pm Thursday 19th at Joe Perks

@peterjwest suggested we have a planning session in Joe Perks (and pointed out that there is a noodle night tomorrow).

@spikeheap - you're the captain of this meet;  are you free tomorrow?

Any other @jsoxford/jsoxforders are welcome to come along.

**Comment by spikeheap** [comment]
@benfoxall (un)fortunately I'm in the Swiss Alps at the moment, so can't make tomorrow. I'm ski-touring next week so will be properly out of communication, but I'm back the following week. 
![img_4547](https://cloud.githubusercontent.com/assets/464482/6251059/f207ade2-b791-11e4-8d6e-3f2a7eb5383a.JPG)

I've contacted Leigh about giving a talk on practical open data. He seems keen but hasn't got back to me yet. 

Of course, don't let that stop a planning evening!

**Comment by benfoxall** [comment]
Up on Meetup! Not announced yet (let's do that tomorrow afternoon when everyone's hanging about at work).

http://www.meetup.com/JSOxford/events/220784454/

If anyone spots any typos, or has anything to add, let me know.

**Comment by benfoxall** [comment]
Announced!

@spikeheap - I took off the BOOYA, and left it up to you when you're back to work out if we need something extra.

Another option is for me to give a shot talk about some technical aspects behind my jQuk talk; not really on topic - but might be kind of timely.

**Comment by AverageMarcus** [comment]
How about a "highlights from JQUK" discussion? (For those that were there and that weren't)

**Comment by spikeheap** [comment]
:+1: @AverageMarcus & @benfoxall for JQUK-inspired additions, particularly a slightly techier look into some of your talk @benfoxall, but you've got quite a bit on in the lead-up already...

**Comment by benfoxall** [comment]
We could have a generic "**jQueryUK debrief**" - and you can work out what that consists of down the line?  Either highlights, some of my stuff, or a summary of stuff?

Might be good to encourage people to come along on Friday

**Comment by AverageMarcus** [comment]
How about a demo of Foxall Storage? You have some liquid metal, yes?

**Comment by benfoxall** [comment]
I'm not actually sure if we've got any mercury kicking round the office - however:

> [Alan Turing proposed the use of gin as an ultrasonic delay medium, claiming that it had the necessary acoustic properties.](http://en.wikipedia.org/wiki/Delay_line_memory#Mercury_delay_lines)

Turing was a dude

**Comment by AverageMarcus** [comment]
I could prob bring some Gin

**Comment by benfoxall** [comment]
nicely done everyone!
